version: '3.5'

services:
  db:
    image: postgis/postgis
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db:/var/lib/posgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db

volumes:
  db:
    driver: local
